### ISSUE TITLE
[Snake] Phantom fruit bug/gamemode

### ISSUE THREAD

**Issue by Trickiy** [Wolfyxon/3ds-web-stuff#53]
When I start and eat a fruit then die when the fruit is next to a wall the fruit will stay till next run with a second but eating the phantom fruit will not count to the score counter. This would be a interesting gamemode where two fruits spawn at once but only one is real and when the real one is eaten the phantom fruit will move spots to keep the player on there toes.

**Comment by Wolfyxon** [comment]
It's not going to be easy to debug. It doesn't always happen when a fruit is next to a wall.
I'll try to fix it though.

**Comment by Wolfyxon** [comment]
@magiczocker10 could you also look into that since you made snake?

**Comment by Trickiy** [comment]
If you had some sort of terminal on the bottom screen showing all the code that being exicuted then it would most likely be easier to debug.

**Comment by Wolfyxon** [comment]
Well that's not quite possible on the 3DS browser. 
We use `alert()` to show messages and values for debugging instead.

**Comment by magiczocker10** [comment]
I can take a look later. Maybe we should switch back to clear everything, instead of redrawing only needed pixels. Might just be a bug with foodX and foodY.

Current food clearing on reset: https://github.com/Wolfyxon/3ds-web-stuff/blob/main/games/snake/snake.js#L74

This code should than be used instead: https://github.com/Wolfyxon/3ds-web-stuff/blob/main/games/snake/snake.js#L34

**Comment by magiczocker10** [comment]
Found the issue. Its just a wrong check for food. I used `foodX && foodY` instead of `foodX > -1 && foodY > -1` in line 74.

**Comment by Wolfyxon** [comment]
Alright nice. Should be fixed now.
